var LESSONS = [

{id:0,icon:'🖨️',title:'Print & Output',sub:'Make Python talk',xp:60,tier:0,slides:[
  {type:'learn',title:'Welcome to Python Quest!',body:'<p>Python is one of the most popular programming languages in the world, used for <b style="color:var(--a)">websites, AI, data science, and automation</b>.</p><p>We start with the most fundamental skill: <b style="color:var(--a2)">printing output</b> using the <code style="color:var(--a);background:var(--s2);padding:1px 5px;border-radius:4px;font-family:Space Mono,monospace">print()</code> function.</p>'},
  {type:'learn',title:'The print() Function',body:'<p>Wrap text in <b style="color:var(--a)">print()</b> with quotes:</p><div class="code-block"><pre><span class="fn">print</span>(<span class="str">"Hello, World!"</span>)\n<span class="fn">print</span>(<span class="str">"Python is awesome"</span>)\n<span class="fn">print</span>(<span class="num">42</span>)</pre></div><p>Text goes in quotes. Numbers do not. Each print() outputs on its own <b style="color:var(--a2)">new line</b>. Lines starting with <b style="color:var(--a)">#</b> are comments Python ignores.</p>'},
  {type:'quiz',q:'Which correctly prints the word Python?',opts:['print(Python)','print("Python")','Print("Python")','echo "Python"'],correct:1,ok:'Correct! Text must be in quotes. Python is case-sensitive so Print with a capital P would error.',bad:'Not quite. Text must be in quotes: print("Python"). It is lowercase print.'},
  {type:'code',title:'Try It: Your First Print',inst:'Write a print statement that outputs: Hello, I am learning Python!',hint:'print("Hello, I am learning Python!")',check:function(c){return c.indexOf('print')>=0&&(c.indexOf('Hello')>=0||c.indexOf('hello')>=0);},msg:'Use print() with your message inside straight quotes.'},
]},

{id:1,icon:'📦',title:'Variables',sub:'Storing information',xp:60,tier:0,slides:[
  {type:'learn',title:'What Is a Variable?',body:'<p>A <b style="color:var(--a)">variable</b> is a named box that stores a value:</p><div class="code-block"><pre><span class="id">name</span> = <span class="str">"Mike"</span>\n<span class="id">age</span> = <span class="num">30</span>\n<span class="fn">print</span>(<span class="id">name</span>)   <span class="cmt"># Mike</span>\n<span class="fn">print</span>(<span class="id">age</span>)    <span class="cmt"># 30</span></pre></div><p>The <b style="color:var(--a)">=</b> sign assigns a value. It does NOT mean equals like in math.</p>'},
  {type:'learn',title:'f-Strings',body:'<p>Put <b style="color:var(--a)">f</b> before a quote and use <b style="color:var(--a2)">{}</b> to embed variables:</p><div class="code-block"><pre><span class="id">name</span> = <span class="str">"Mike"</span>\n<span class="id">score</span> = <span class="num">95</span>\n<span class="fn">print</span>(<span class="str">f"Player: {name}, Score: {score}"</span>)\n<span class="cmt"># Player: Mike, Score: 95</span></pre></div><p>iPhone tip: use <b style="color:var(--a3)">straight quotes</b> not curly ones. Turn off Smart Punctuation in Settings > General > Keyboard.</p>'},
  {type:'quiz',q:'color = "blue"\nprint(f"The sky is {color}")\n\nWhat is printed?',opts:['The sky is {color}','The sky is color','The sky is blue','Error'],correct:2,ok:'Correct! The f-string replaces {color} with the value: blue.',bad:'With f-strings, {color} gets replaced by the variable value. Output: The sky is blue.'},
  {type:'code',title:'Challenge: Introduce Yourself',inst:'Create a variable called <b style="color:var(--a)">name</b>, store your name, then use an f-string to print: Hi, my name is [name]',hint:'name = "Mike"\nprint(f"Hi, my name is {name}")',check:function(c){return (c.indexOf('f"')>=0||c.indexOf("f'")>=0)&&c.indexOf('name')>=0;},msg:'Use an f-string (straight f" not curly) and {name} in curly braces.'},
]},

{id:2,icon:'🔢',title:'Data Types',sub:'int, float, string, bool',xp:70,tier:0,slides:[
  {type:'learn',title:'The 4 Core Data Types',body:'<div class="code-block"><pre><span class="id">score</span> = <span class="num">42</span>        <span class="cmt"># int - whole number</span>\n<span class="id">price</span> = <span class="num">9.99</span>      <span class="cmt"># float - decimal</span>\n<span class="id">name</span> = <span class="str">"Alice"</span>    <span class="cmt"># str - text</span>\n<span class="id">active</span> = <span class="kw">True</span>     <span class="cmt"># bool - True/False</span></pre></div><p>Python figures out the type automatically.</p>'},
  {type:'learn',title:'Type Conversion',body:'<div class="code-block"><pre><span class="id">x</span> = <span class="str">"42"</span>\n<span class="id">y</span> = <span class="fn">int</span>(<span class="id">x</span>)     <span class="cmt"># "42" to 42</span>\n<span class="id">z</span> = <span class="fn">float</span>(<span class="id">x</span>)   <span class="cmt"># "42" to 42.0</span>\n<span class="id">s</span> = <span class="fn">str</span>(<span class="num">99</span>)     <span class="cmt"># 99 to "99"</span></pre></div><p>Critical: user input is ALWAYS a string. Convert with int() or float() before doing math.</p>'},
  {type:'quiz',q:'x = "5"\nprint(x + x)\n\nWhat is the result?',opts:['10','"10"','55','Error'],correct:2,ok:'Correct! x is a string. + on strings means joining: "5"+"5" = "55".',bad:'x="5" is a string. + joins strings: "5"+"5"="55". To add numbers: int(x)+int(x)=10.'},
  {type:'quiz',q:'What does print(10 % 3) output?',opts:['3','1','0.33','3.33'],correct:1,ok:'Correct! % is modulo - it returns the remainder. 10 divided by 3 = 3 remainder 1.',bad:'% returns the remainder after division. 10 divided by 3 = 3 remainder 1, so 10 % 3 = 1.'},
]},

{id:3,icon:'⌨️',title:'User Input',sub:'Getting data from users',xp:70,tier:0,slides:[
  {type:'learn',title:'The input() Function',body:'<div class="code-block"><pre><span class="id">name</span> = <span class="fn">input</span>(<span class="str">"What is your name? "</span>)\n<span class="fn">print</span>(<span class="str">f"Hello, {name}!"</span>)</pre></div><p>input() ALWAYS returns a string even if the user types a number. Convert with int() or float() to do math.</p>'},
  {type:'quiz',q:'Which correctly asks for age and prints next year\'s age?',opts:['age = input("Age: ")\nprint(age + 1)','age = int(input("Age: "))\nprint(age + 1)','age = str(input("Age: "))\nprint(age + 1)','age = float(input("Age: "))\nprint(age)'],correct:1,ok:'Correct! int(input()) converts the string to an integer so you can do math.',bad:'input() returns a string. You cannot add 1 to a string. Use int(input()) to convert first.'},
  {type:'learn',title:'Putting It Together',body:'<div class="code-block"><pre><span class="id">name</span> = <span class="fn">input</span>(<span class="str">"Your name: "</span>)\n<span class="id">year</span> = <span class="fn">int</span>(<span class="fn">input</span>(<span class="str">"Birth year: "</span>))\n<span class="id">age</span> = <span class="num">2025</span> - <span class="id">year</span>\n<span class="fn">print</span>(<span class="str">f"Hi {name}! You are about {age} years old."</span>)</pre></div><p>Ask, then process, then display. This is the core loop of most programs!</p>'},
]},

{id:4,icon:'🔀',title:'Conditionals',sub:'if / elif / else',xp:80,tier:0,slides:[
  {type:'learn',title:'if and else',body:'<div class="code-block"><pre><span class="id">temp</span> = <span class="num">15</span>\n<span class="kw">if</span> <span class="id">temp</span> > <span class="num">20</span>:\n    <span class="fn">print</span>(<span class="str">"T-shirt"</span>)\n<span class="kw">else</span>:\n    <span class="fn">print</span>(<span class="str">"Jacket"</span>)</pre></div><p>The colon and 4-space indent are required. Only one branch ever runs.</p>'},
  {type:'learn',title:'elif and Comparison Operators',body:'<div class="code-block"><pre><span class="id">score</span> = <span class="num">75</span>\n<span class="kw">if</span> <span class="id">score</span> >= <span class="num">90</span>:\n    <span class="fn">print</span>(<span class="str">"A"</span>)\n<span class="kw">elif</span> <span class="id">score</span> >= <span class="num">70</span>:\n    <span class="fn">print</span>(<span class="str">"C"</span>)  <span class="cmt"># runs</span>\n<span class="kw">else</span>:\n    <span class="fn">print</span>(<span class="str">"F"</span>)\n\n<span class="cmt"># Operators: == != > < >= <=</span>\n<span class="cmt"># Use == to compare, = to assign!</span></pre></div>'},
  {type:'quiz',q:'x = 10\n\nif x > 5:\n    print("big")\nelse:\n    print("small")\n\nWhat prints?',opts:['small','big','big then small','Error'],correct:1,ok:'Correct! 10 > 5 is True so the if block runs.',bad:'10 > 5 is True so Python prints big. The else is skipped.'},
  {type:'code',title:'Challenge: Grade Checker',inst:'Write if/elif/else that prints A for score>=90, B for >=80, C for >=70, or F otherwise. Set score=85.',hint:'score = 85\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")\nelse:\n    print("F")',check:function(c){return c.indexOf('if')>=0&&c.indexOf('elif')>=0&&c.indexOf('else')>=0;},msg:'Use if, elif, and else. Remember the colon and indentation.'},
]},

{id:5,icon:'🔁',title:'Loops',sub:'while and for',xp:80,tier:0,slides:[
  {type:'learn',title:'while and for',body:'<div class="code-block"><pre><span class="cmt"># while - runs as long as condition is True</span>\n<span class="id">count</span> = <span class="num">1</span>\n<span class="kw">while</span> <span class="id">count</span> <= <span class="num">3</span>:\n    <span class="fn">print</span>(<span class="id">count</span>)\n    <span class="id">count</span> += <span class="num">1</span>   <span class="cmt"># 1, 2, 3</span>\n\n<span class="cmt"># for - iterates a set number of times</span>\n<span class="kw">for</span> <span class="id">i</span> <span class="kw">in</span> <span class="fn">range</span>(<span class="num">1</span>, <span class="num">4</span>):\n    <span class="fn">print</span>(<span class="id">i</span>)      <span class="cmt"># 1, 2, 3</span></pre></div><p>range(1,4) means 1 up to but not including 4.</p>'},
  {type:'quiz',q:'for i in range(2, 6):\n    print(i)\n\nHow many numbers are printed?',opts:['3','4','5','6'],correct:1,ok:'Correct! range(2,6) = 2,3,4,5 which is four numbers. End is excluded.',bad:'range(2,6) gives 2,3,4,5 which is 4 numbers. The end (6) is not included.'},
  {type:'code',title:'Challenge: Multiplication Table',inst:'Use a for loop to print the 3 times table from 1x3 to 5x3. Output: 3, 6, 9, 12, 15',hint:'for i in range(1, 6):\n    print(i * 3)',check:function(c){return c.indexOf('for')>=0&&c.indexOf('range')>=0;},msg:'Use a for loop with range(1, 6) and multiply i by 3.'},
]},

{id:6,icon:'📋',title:'Lists',sub:'Collections of data',xp:80,tier:0,slides:[
  {type:'learn',title:'Lists and Indexing',body:'<div class="code-block"><pre><span class="id">fruits</span> = [<span class="str">"apple"</span>, <span class="str">"banana"</span>, <span class="str">"cherry"</span>]\n<span class="cmt">#            [0]         [1]         [2]</span>\n\n<span class="fn">print</span>(<span class="id">fruits</span>[<span class="num">0</span>])    <span class="cmt"># apple</span>\n<span class="fn">print</span>(<span class="id">fruits</span>[-<span class="num">1</span>])   <span class="cmt"># cherry (last!)</span>\n<span class="fn">print</span>(<span class="fn">len</span>(<span class="id">fruits</span>))  <span class="cmt"># 3</span></pre></div><p>Python counts from 0! Negative indexes count from the end.</p>'},
  {type:'learn',title:'Modifying and Looping',body:'<div class="code-block"><pre><span class="id">nums</span> = [<span class="num">10</span>, <span class="num">20</span>, <span class="num">30</span>]\n<span class="id">nums</span>.<span class="fn">append</span>(<span class="num">40</span>)   <span class="cmt"># [10,20,30,40]</span>\n<span class="id">nums</span>.<span class="fn">remove</span>(<span class="num">20</span>)   <span class="cmt"># [10,30,40]</span>\n<span class="id">nums</span>[<span class="num">0</span>] = <span class="num">99</span>      <span class="cmt"># [99,30,40]</span>\n\n<span class="kw">for</span> <span class="id">n</span> <span class="kw">in</span> <span class="id">nums</span>:\n    <span class="fn">print</span>(<span class="id">n</span>)       <span class="cmt"># 99, 30, 40</span></pre></div>'},
  {type:'quiz',q:'colors = ["red", "green", "blue"]\ncolors.append("yellow")\n\nWhat is colors[-1]?',opts:['"red"','"blue"','"yellow"','Error'],correct:2,ok:'Correct! append() adds to the end. -1 always refers to the last item which is now "yellow".',bad:'append("yellow") adds to end making ["red","green","blue","yellow"]. -1 = last = "yellow".'},
  {type:'code',title:'Challenge: List Builder',inst:'Create a list called <b style="color:var(--a)">scores</b> with values 85, 92, 78, 95. Then loop through it and print each score.',hint:'scores = [85, 92, 78, 95]\nfor score in scores:\n    print(score)',check:function(c){return c.indexOf('scores')>=0&&c.indexOf('for')>=0;},msg:'Create the list then use a for loop to iterate through it.'},
]},

{id:7,icon:'⚙️',title:'Functions',sub:'Reusable blocks of code',xp:90,tier:0,slides:[
  {type:'learn',title:'Defining and Calling',body:'<div class="code-block"><pre><span class="kw">def</span> <span class="fn">greet</span>(<span class="id">name</span>):\n    <span class="fn">print</span>(<span class="str">f"Hello, {name}!"</span>)\n\n<span class="fn">greet</span>(<span class="str">"Mike"</span>)    <span class="cmt"># Hello, Mike!</span>\n<span class="fn">greet</span>(<span class="str">"Alice"</span>)   <span class="cmt"># Hello, Alice!</span></pre></div><p>def defines it. The name in parentheses is the parameter. The value you pass when calling is the argument.</p>'},
  {type:'learn',title:'The return Statement',body:'<div class="code-block"><pre><span class="kw">def</span> <span class="fn">square</span>(<span class="id">n</span>):\n    <span class="kw">return</span> <span class="id">n</span> * <span class="id">n</span>\n\n<span class="id">result</span> = <span class="fn">square</span>(<span class="num">5</span>)\n<span class="fn">print</span>(<span class="id">result</span>)          <span class="cmt"># 25</span>\n<span class="fn">print</span>(<span class="fn">square</span>(<span class="num">4</span>) + <span class="num">1</span>)   <span class="cmt"># 17</span></pre></div><p>return sends a value back so you can use it elsewhere. Without it the function returns None.</p>'},
  {type:'quiz',q:'def double(n):\n    return n * 2\n\nprint(double(double(3)))\n\nWhat prints?',opts:['6','9','12','Error'],correct:2,ok:'Correct! double(3)=6, then double(6)=12. Functions can be nested!',bad:'Work inside out: double(3)=6, then double(6)=12.'},
  {type:'code',title:'Challenge: BMI Calculator',inst:'Write a function called <b style="color:var(--a)">bmi</b> that takes weight_kg and height_m and returns weight divided by height squared. Call it with bmi(70, 1.75) and print the result.',hint:'def bmi(weight_kg, height_m):\n    return weight_kg / (height_m ** 2)\n\nresult = bmi(70, 1.75)\nprint(result)',check:function(c){return c.indexOf('def bmi')>=0&&c.indexOf('return')>=0;},msg:'Define a function called bmi that uses return. Divide weight by height squared (**2).'},
]},

{id:8,icon:'📖',title:'Dictionaries',sub:'Key-value data',xp:90,tier:1,slides:[
  {type:'learn',title:'What Is a Dictionary?',body:'<p>A <b style="color:var(--a)">dictionary</b> stores data as <b style="color:var(--a2)">key: value</b> pairs:</p><div class="code-block"><pre><span class="id">person</span> = {\n    <span class="str">"name"</span>: <span class="str">"Mike"</span>,\n    <span class="str">"age"</span>: <span class="num">30</span>,\n    <span class="str">"city"</span>: <span class="str">"Boston"</span>\n}\n\n<span class="fn">print</span>(<span class="id">person</span>[<span class="str">"name"</span>])   <span class="cmt"># Mike</span>\n<span class="fn">print</span>(<span class="id">person</span>[<span class="str">"age"</span>])    <span class="cmt"># 30</span></pre></div><p>Access values using their key in square brackets.</p>'},
  {type:'learn',title:'Adding, Updating and Looping',body:'<div class="code-block"><pre><span class="id">person</span> = {<span class="str">"name"</span>: <span class="str">"Mike"</span>, <span class="str">"age"</span>: <span class="num">30</span>}\n\n<span class="id">person</span>[<span class="str">"email"</span>] = <span class="str">"mike@x.com"</span>  <span class="cmt"># add</span>\n<span class="id">person</span>[<span class="str">"age"</span>] = <span class="num">31</span>              <span class="cmt"># update</span>\n\n<span class="kw">for</span> <span class="id">key</span>, <span class="id">value</span> <span class="kw">in</span> <span class="id">person</span>.<span class="fn">items</span>():\n    <span class="fn">print</span>(<span class="str">f"{key}: {value}"</span>)</pre></div>'},
  {type:'learn',title:'Useful Methods',body:'<div class="code-block"><pre><span class="id">d</span> = {<span class="str">"a"</span>: <span class="num">1</span>, <span class="str">"b"</span>: <span class="num">2</span>, <span class="str">"c"</span>: <span class="num">3</span>}\n\n<span class="fn">print</span>(<span class="id">d</span>.<span class="fn">keys</span>())       <span class="cmt"># dict_keys(["a","b","c"])</span>\n<span class="fn">print</span>(<span class="id">d</span>.<span class="fn">values</span>())     <span class="cmt"># dict_values([1, 2, 3])</span>\n<span class="fn">print</span>(<span class="str">"a"</span> <span class="kw">in</span> <span class="id">d</span>)       <span class="cmt"># True</span>\n<span class="fn">print</span>(<span class="id">d</span>.<span class="fn">get</span>(<span class="str">"z"</span>, <span class="num">0</span>)) <span class="cmt"># 0 (safe default)</span></pre></div><p>d.get(key, default) is safer than d[key] because it returns a default instead of crashing if the key does not exist.</p>'},
  {type:'quiz',q:'d = {"x": 10, "y": 20}\nd["x"] = 99\nprint(d["x"] + d["y"])\n\nWhat prints?',opts:['30','119','109','Error'],correct:1,ok:'Correct! d["x"] was updated to 99. 99 + 20 = 119.',bad:'d["x"] = 99 updates the value. So d["x"]+d["y"] = 99+20 = 119.'},
  {type:'code',title:'Challenge: Contact Book',inst:'Create a dictionary called <b style="color:var(--a)">contact</b> with keys "name", "phone", and "email". Then print each key-value pair using a for loop and .items().',hint:'contact = {\n    "name": "Mike",\n    "phone": "555-1234",\n    "email": "mike@example.com"\n}\n\nfor key, value in contact.items():\n    print(f"{key}: {value}")',check:function(c){return c.indexOf('contact')>=0&&c.indexOf('.items()')>=0;},msg:'Create the dictionary then loop with .items() to get key-value pairs.'},
]},

{id:9,icon:'🔤',title:'String Methods',sub:'Manipulating text',xp:90,tier:1,slides:[
  {type:'learn',title:'Common String Methods',body:'<p>Strings have built-in methods you call with a dot:</p><div class="code-block"><pre><span class="id">s</span> = <span class="str">"  Hello, World!  "</span>\n\n<span class="fn">print</span>(<span class="id">s</span>.<span class="fn">strip</span>())         <span class="cmt"># "Hello, World!"</span>\n<span class="fn">print</span>(<span class="id">s</span>.<span class="fn">lower</span>())         <span class="cmt"># "  hello, world!  "</span>\n<span class="fn">print</span>(<span class="id">s</span>.<span class="fn">upper</span>())         <span class="cmt"># "  HELLO, WORLD!  "</span>\n<span class="fn">print</span>(<span class="id">s</span>.<span class="fn">replace</span>(<span class="str">"World"</span>, <span class="str">"Python"</span>))</pre></div>'},
  {type:'learn',title:'split, join and find',body:'<div class="code-block"><pre><span class="id">sentence</span> = <span class="str">"the quick brown fox"</span>\n\n<span class="id">words</span> = <span class="id">sentence</span>.<span class="fn">split</span>()\n<span class="fn">print</span>(<span class="id">words</span>)   <span class="cmt"># ["the","quick","brown","fox"]</span>\n\n<span class="fn">print</span>(<span class="str">"-"</span>.<span class="fn">join</span>(<span class="id">words</span>))\n<span class="cmt"># the-quick-brown-fox</span>\n\n<span class="fn">print</span>(<span class="str">"quick"</span> <span class="kw">in</span> <span class="id">sentence</span>)  <span class="cmt"># True</span></pre></div>'},
  {type:'learn',title:'String Slicing',body:'<p>Extract parts of a string using slicing:</p><div class="code-block"><pre><span class="id">s</span> = <span class="str">"Python"</span>\n<span class="cmt"># P y t h o n</span>\n<span class="cmt"># 0 1 2 3 4 5</span>\n\n<span class="fn">print</span>(<span class="id">s</span>[<span class="num">0</span>:<span class="num">3</span>])    <span class="cmt"># "Pyt"</span>\n<span class="fn">print</span>(<span class="id">s</span>[<span class="num">2</span>:])     <span class="cmt"># "thon"</span>\n<span class="fn">print</span>(<span class="id">s</span>[:<span class="num">3</span>])     <span class="cmt"># "Pyt"</span>\n<span class="fn">print</span>(<span class="id">s</span>[::-<span class="num">1</span>])   <span class="cmt"># "nohtyP" reversed!</span></pre></div>'},
  {type:'quiz',q:'"  python  ".strip().upper()\n\nWhat is the result?',opts:['"  PYTHON  "','"PYTHON"','"python"','Error'],correct:1,ok:'Correct! strip() removes whitespace giving "python", then upper() gives "PYTHON".',bad:'strip() removes spaces giving "python", then upper() capitalises giving "PYTHON".'},
  {type:'code',title:'Challenge: Name Formatter',inst:'Ask the user for their full name. Print it 1) in ALL CAPS and 2) with the words reversed (e.g. "John Smith" becomes "Smith John").',hint:'name = input("Full name: ")\nprint(name.upper())\nwords = name.split()\nwords.reverse()\nprint(" ".join(words))',check:function(c){return c.indexOf('.upper()')>=0&&c.indexOf('.split()')>=0;},msg:'Use .upper() for caps and .split() to break into words, then .join() to reassemble.'},
]},

{id:10,icon:'🛡️',title:'Error Handling',sub:'try / except',xp:100,tier:1,slides:[
  {type:'learn',title:'Why Programs Crash',body:'<p>Without error handling, bad input crashes your program:</p><div class="code-block"><pre><span class="id">age</span> = <span class="fn">int</span>(<span class="fn">input</span>(<span class="str">"Age: "</span>))\n<span class="cmt"># User types "abc" - CRASH!</span>\n<span class="cmt"># ValueError: invalid literal for int()</span></pre></div><p>Real programs handle errors gracefully using <b style="color:var(--a)">try/except</b>.</p>'},
  {type:'learn',title:'try and except',body:'<div class="code-block"><pre><span class="kw">try</span>:\n    <span class="id">age</span> = <span class="fn">int</span>(<span class="fn">input</span>(<span class="str">"Age: "</span>))\n    <span class="fn">print</span>(<span class="str">f"Next year: {age+1}"</span>)\n<span class="kw">except</span> ValueError:\n    <span class="fn">print</span>(<span class="str">"Please enter a valid number!"</span>)</pre></div><p>Python tries the code. If a ValueError occurs it catches it and runs the except block instead of crashing.</p>'},
  {type:'learn',title:'Multiple Exceptions and finally',body:'<div class="code-block"><pre><span class="kw">try</span>:\n    <span class="id">num</span> = <span class="fn">int</span>(<span class="fn">input</span>(<span class="str">"Number: "</span>))\n    <span class="id">result</span> = <span class="num">100</span> / <span class="id">num</span>\n    <span class="fn">print</span>(<span class="id">result</span>)\n<span class="kw">except</span> ValueError:\n    <span class="fn">print</span>(<span class="str">"Not a number!"</span>)\n<span class="kw">except</span> ZeroDivisionError:\n    <span class="fn">print</span>(<span class="str">"Cannot divide by zero!"</span>)\n<span class="kw">finally</span>:\n    <span class="fn">print</span>(<span class="str">"Done."</span>)  <span class="cmt"># always runs</span></pre></div>'},
  {type:'quiz',q:'try:\n    x = 10 / 0\nexcept ZeroDivisionError:\n    print("Cannot divide by zero")\n\nWhat happens?',opts:['The program crashes','Prints: Cannot divide by zero','Prints: 0','Nothing happens'],correct:1,ok:'Correct! 10/0 raises ZeroDivisionError. The except block catches it and prints the message.',bad:'10/0 raises ZeroDivisionError. The except block catches it so there is no crash.'},
  {type:'code',title:'Challenge: Safe Division',inst:'Write a function called <b style="color:var(--a)">safe_divide</b> that takes two numbers and returns the result of dividing the first by the second. If division by zero is attempted, return the string "Cannot divide by zero" instead of crashing.',hint:'def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return "Cannot divide by zero"\n\nprint(safe_divide(10, 2))   # 5.0\nprint(safe_divide(10, 0))   # Cannot divide by zero',check:function(c){return c.indexOf('try')>=0&&c.indexOf('except')>=0&&c.indexOf('def safe_divide')>=0;},msg:'Define safe_divide with a try/except block catching ZeroDivisionError.'},
]},

{id:11,icon:'⚡',title:'List Comprehensions',sub:'Pythonic shortcuts',xp:100,tier:2,slides:[
  {type:'learn',title:'The Old Way vs The Pythonic Way',body:'<p>A <b style="color:var(--a)">list comprehension</b> builds a list in one line:</p><div class="code-block"><pre><span class="cmt"># Old way - 4 lines</span>\n<span class="id">squares</span> = []\n<span class="kw">for</span> <span class="id">i</span> <span class="kw">in</span> <span class="fn">range</span>(<span class="num">1</span>, <span class="num">6</span>):\n    <span class="id">squares</span>.<span class="fn">append</span>(<span class="id">i</span> ** <span class="num">2</span>)\n\n<span class="cmt"># Pythonic way - 1 line!</span>\n<span class="id">squares</span> = [<span class="id">i</span> ** <span class="num">2</span> <span class="kw">for</span> <span class="id">i</span> <span class="kw">in</span> <span class="fn">range</span>(<span class="num">1</span>, <span class="num">6</span>)]\n\n<span class="fn">print</span>(<span class="id">squares</span>)  <span class="cmt"># [1, 4, 9, 16, 25]</span></pre></div><p>Syntax: <b style="color:var(--a2)">[expression for item in iterable]</b></p>'},
  {type:'learn',title:'Adding a Condition',body:'<div class="code-block"><pre><span class="id">nums</span> = [<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>, <span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>]\n\n<span class="cmt"># Only even numbers</span>\n<span class="id">evens</span> = [<span class="id">n</span> <span class="kw">for</span> <span class="id">n</span> <span class="kw">in</span> <span class="id">nums</span> <span class="kw">if</span> <span class="id">n</span> % <span class="num">2</span> == <span class="num">0</span>]\n<span class="fn">print</span>(<span class="id">evens</span>)   <span class="cmt"># [2, 4, 6]</span>\n\n<span class="cmt"># Uppercase words longer than 3 chars</span>\n<span class="id">words</span> = [<span class="str">"hi"</span>, <span class="str">"python"</span>, <span class="str">"ok"</span>, <span class="str">"code"</span>]\n<span class="id">long</span> = [<span class="id">w</span>.<span class="fn">upper</span>() <span class="kw">for</span> <span class="id">w</span> <span class="kw">in</span> <span class="id">words</span> <span class="kw">if</span> <span class="fn">len</span>(<span class="id">w</span>) > <span class="num">3</span>]\n<span class="fn">print</span>(<span class="id">long</span>)    <span class="cmt"># ["PYTHON", "CODE"]</span></pre></div>'},
  {type:'quiz',q:'result = [x * 2 for x in range(4)]\nprint(result)\n\nWhat prints?',opts:['[0, 2, 4, 6]','[2, 4, 6, 8]','[1, 2, 3, 4]','[0, 1, 2, 3]'],correct:0,ok:'Correct! range(4) = 0,1,2,3. Each multiplied by 2 gives [0,2,4,6].',bad:'range(4) gives 0,1,2,3. Multiply each by 2 to get [0,2,4,6].'},
  {type:'code',title:'Challenge: Comprehension Workout',inst:'Using a list comprehension, create a list called <b style="color:var(--a)">long_words</b> containing only words with more than 4 characters from: ["cat", "elephant", "dog", "python", "ox"]',hint:'words = ["cat", "elephant", "dog", "python", "ox"]\nlong_words = [w for w in words if len(w) > 4]\nprint(long_words)  # ["elephant", "python"]',check:function(c){return c.indexOf('for')>=0&&c.indexOf('if')>=0&&c.indexOf('len')>=0;},msg:'Use [w for w in words if len(w) > 4]. The condition goes at the end.'},
]},

{id:12,icon:'📦',title:'Modules & Imports',sub:"Python's built-in libraries",xp:100,tier:2,slides:[
  {type:'learn',title:'What Is a Module?',body:'<p>Python comes with hundreds of built-in <b style="color:var(--a)">modules</b>. Import them with <b style="color:var(--a2)">import</b>:</p><div class="code-block"><pre><span class="kw">import</span> math\n\n<span class="fn">print</span>(math.<span class="fn">sqrt</span>(<span class="num">16</span>))    <span class="cmt"># 4.0</span>\n<span class="fn">print</span>(math.pi)            <span class="cmt"># 3.14159...</span>\n<span class="fn">print</span>(math.<span class="fn">floor</span>(<span class="num">3.7</span>))  <span class="cmt"># 3</span>\n<span class="fn">print</span>(math.<span class="fn">ceil</span>(<span class="num">3.2</span>))   <span class="cmt"># 4</span></pre></div>'},
  {type:'learn',title:'random and datetime',body:'<div class="code-block"><pre><span class="kw">import</span> random\n<span class="kw">import</span> datetime\n\n<span class="fn">print</span>(random.<span class="fn">randint</span>(<span class="num">1</span>, <span class="num">10</span>))\n<span class="fn">print</span>(random.<span class="fn">choice</span>([<span class="str">"a"</span>,<span class="str">"b"</span>,<span class="str">"c"</span>]))\n\n<span class="id">today</span> = datetime.date.<span class="fn">today</span>()\n<span class="fn">print</span>(<span class="id">today</span>)         <span class="cmt"># 2025-04-21</span>\n<span class="fn">print</span>(<span class="id">today</span>.year)    <span class="cmt"># 2025</span></pre></div>'},
  {type:'learn',title:'from X import Y and aliases',body:'<div class="code-block"><pre><span class="cmt"># Import just what you need</span>\n<span class="kw">from</span> math <span class="kw">import</span> sqrt, pi\n<span class="fn">print</span>(<span class="fn">sqrt</span>(<span class="num">25</span>))   <span class="cmt"># 5.0 - no math. prefix needed</span>\n\n<span class="cmt"># Alias with as</span>\n<span class="kw">import</span> random <span class="kw">as</span> r\n<span class="fn">print</span>(r.<span class="fn">randint</span>(<span class="num">1</span>, <span class="num">100</span>))</pre></div><p>You will see import numpy as np and import pandas as pd constantly in data science code.</p>'},
  {type:'quiz',q:'from math import sqrt\nprint(sqrt(81))\n\nWhat prints?',opts:['math.sqrt(81)','9','9.0','Error'],correct:2,ok:'Correct! sqrt(81) = 9.0 (a float). "from X import Y" lets you use Y directly without the module prefix.',bad:'sqrt(81) = 9.0. "from math import sqrt" imports sqrt directly so you call it without math.'},
  {type:'code',title:'Challenge: Random Game',inst:'Use the <b style="color:var(--a)">random</b> module to generate a random number between 1 and 20, store it in <b style="color:var(--a2)">secret</b>, then ask the user to guess. Print Correct! or Wrong! based on their answer.',hint:'import random\nsecret = random.randint(1, 20)\nguess = int(input("Guess (1-20): "))\nif guess == secret:\n    print("Correct!")\nelse:\n    print(f"Wrong! It was {secret}")',check:function(c){return c.indexOf('import random')>=0&&c.indexOf('randint')>=0;},msg:'Import random and use random.randint(1, 20) to generate the secret number.'},
]},

{id:13,icon:'🏗️',title:'Classes & OOP',sub:'Object-oriented programming',xp:120,tier:2,slides:[
  {type:'learn',title:'What Is a Class?',body:'<p>A <b style="color:var(--a)">class</b> is a blueprint for creating objects:</p><div class="code-block"><pre><span class="kw">class</span> <span class="fn">Dog</span>:\n    <span class="kw">def</span> <span class="fn">__init__</span>(<span class="id">self</span>, <span class="id">name</span>, <span class="id">age</span>):\n        <span class="id">self</span>.name = <span class="id">name</span>\n        <span class="id">self</span>.age = <span class="id">age</span>\n\n    <span class="kw">def</span> <span class="fn">bark</span>(<span class="id">self</span>):\n        <span class="fn">print</span>(<span class="str">f"{self.name} says Woof!"</span>)\n\n<span class="id">my_dog</span> = <span class="fn">Dog</span>(<span class="str">"Rex"</span>, <span class="num">3</span>)\n<span class="id">my_dog</span>.<span class="fn">bark</span>()      <span class="cmt"># Rex says Woof!</span>\n<span class="fn">print</span>(<span class="id">my_dog</span>.name)  <span class="cmt"># Rex</span></pre></div>'},
  {type:'learn',title:'__init__ and self',body:'<p><b style="color:var(--a)">__init__</b> runs automatically when you create an object. <b style="color:var(--a2)">self</b> refers to the object itself.</p><div class="code-block"><pre><span class="kw">class</span> <span class="fn">BankAccount</span>:\n    <span class="kw">def</span> <span class="fn">__init__</span>(<span class="id">self</span>, <span class="id">owner</span>, <span class="id">balance</span>=<span class="num">0</span>):\n        <span class="id">self</span>.owner = <span class="id">owner</span>\n        <span class="id">self</span>.balance = <span class="id">balance</span>\n\n    <span class="kw">def</span> <span class="fn">deposit</span>(<span class="id">self</span>, <span class="id">amount</span>):\n        <span class="id">self</span>.balance += <span class="id">amount</span>\n        <span class="fn">print</span>(<span class="str">f"Balance: ${self.balance}"</span>)\n\n<span class="id">acc</span> = <span class="fn">BankAccount</span>(<span class="str">"Mike"</span>, <span class="num">100</span>)\n<span class="id">acc</span>.<span class="fn">deposit</span>(<span class="num">50</span>)   <span class="cmt"># Balance: $150</span></pre></div>'},
  {type:'quiz',q:'class Cat:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        print(f"{self.name} says Meow")\n\nc = Cat("Luna")\nc.speak()\n\nWhat prints?',opts:['Cat says Meow','self.name says Meow','Luna says Meow','Error'],correct:2,ok:'Correct! self.name is "Luna" set in __init__. So speak() prints Luna says Meow.',bad:'self.name was set to "Luna" when Cat("Luna") was called. Output: Luna says Meow.'},
  {type:'learn',title:'Multiple Objects and Why OOP?',body:'<div class="code-block"><pre><span class="id">dog1</span> = <span class="fn">Dog</span>(<span class="str">"Rex"</span>, <span class="num">3</span>)\n<span class="id">dog2</span> = <span class="fn">Dog</span>(<span class="str">"Bella"</span>, <span class="num">5</span>)\n\n<span class="id">dog1</span>.<span class="fn">bark</span>()   <span class="cmt"># Rex says Woof!</span>\n<span class="id">dog2</span>.<span class="fn">bark</span>()   <span class="cmt"># Bella says Woof!</span></pre></div><p>Each object has its own data but shares the same methods. OOP helps you model real-world things and keep code organised as projects grow.</p>'},
  {type:'code',title:'Challenge: Build a Class',inst:'Create a class called <b style="color:var(--a)">Rectangle</b> with width and height attributes. Add methods <b style="color:var(--a2)">area()</b> returning width x height and <b style="color:var(--a2)">perimeter()</b> returning 2 x (width + height). Create one instance and print both.',hint:'class Rectangle:\n    def __init__(self, width, height):\n        self.width = width\n        self.height = height\n\n    def area(self):\n        return self.width * self.height\n\n    def perimeter(self):\n        return 2 * (self.width + self.height)\n\nr = Rectangle(4, 6)\nprint(r.area())       # 24\nprint(r.perimeter())  # 20',check:function(c){return c.indexOf('class Rectangle')>=0&&c.indexOf('def area')>=0&&c.indexOf('def perimeter')>=0;},msg:'Define the class with __init__, area(), and perimeter() methods.'},
]},

];

var TIERS = [
  {label:'Beginner — Foundations',range:[0,7]},
  {label:'Intermediate — Core Python',range:[8,10]},
  {label:'Advanced — Pythonic Code',range:[11,13]},
];

var TOTAL_XP = LESSONS.reduce(function(s,l){return s+l.xp;},0);
